# Generated by Django 5.0.6 on 2024-05-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_admin_specification_subject_questionnaire_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
