# Generated by Django 5.0.6 on 2024-05-31 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="highSchoolGPA",
            new_name="high_school_gpa",
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="biggestDifficulty",
            new_name="region",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="choiceFactors",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="biggest_difficulty",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="choice_factors",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="disliked_subjects",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="preferred_living",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="preferred_study_duration",
            field=models.IntegerField(default="4"),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="preferred_subjects",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="university_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "recommendationID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("recommended_branches", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.questionnaire",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Recommendation",
        ),
    ]
