# Generated by Django 5.0.6 on 2024-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_recommendationid_prediction_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="dislikedSubjects",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="preferredSubjects",
        ),
        migrations.AlterField(
            model_name="prediction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
